import { types } from 'node:util';
import { InvoiceDraftCommandError } from '../js/backend/invoiceDraftCommand.js';
import { InvoiceDraftValidationError } from '../js/finance/invoiceDraftValidator.js';

const messages = {
    UNAUTHENTICATED: 'Sign in again.', INVALID_REQUEST: 'Invalid request.',
    INVALID_INVOICE_DRAFT: 'Invalid invoice draft.', REFERENCE_NOT_SUPPORTED: 'Linked references are not supported.',
    BUSINESS_ACCESS_DENIED: 'Business access denied.', BUSINESS_NOT_FOUND: 'Business not found.',
    BUSINESS_INACTIVE: 'Business is inactive.', INVALID_BUSINESS_ROLE: 'Owner role required.',
    INVOICE_ALREADY_EXISTS: 'Invoice ID already exists.', UNAVAILABLE: 'Service temporarily unavailable.',
    INTERNAL: 'Unable to save invoice draft.'
};
export class SaveInvoiceDraftError extends Error {
    constructor(code) {
        super(messages[code] || messages.INTERNAL);
        this.name = 'SaveInvoiceDraftError';
        this.code = Object.hasOwn(messages, code) ? code : 'INTERNAL';
        // This local API returns application errors, never server stack traces.
        delete this.stack;
    }
}
export const fail = code => { throw new SaveInvoiceDraftError(code); };
export const identity = value => typeof value === 'string' && value.length > 0
    && value.isWellFormed() && [...value].length <= 128 && value.trim() === value
    && !/[\u0000-\u001f\u007f-\u009f]/u.test(value);
export const businessIdValid = value => identity(value) && !value.includes('/')
    && !['.', '..'].includes(value) && !/^__.*__$/u.test(value);

// Copy wire data synchronously, without executing accessors, proxies or toJSON.
// A bounded traversal also prevents deeply nested or oversized local inputs.
export function snapshot(value) {
    let bytes = 0;
    const seen = new Set();
    function copy(item, depth) {
        if (depth > 16 || (bytes += 8) > 512 * 1024) fail('INVALID_REQUEST');
        if (item === null || typeof item === 'boolean') return item;
        if (typeof item === 'string') {
            bytes += Buffer.byteLength(item);
            if (bytes > 512 * 1024) fail('INVALID_REQUEST');
            return item;
        }
        if (typeof item === 'number' && Number.isFinite(item)) return item;
        if (!item || typeof item !== 'object' || types.isProxy(item) || seen.has(item)) fail('INVALID_REQUEST');
        const array = Array.isArray(item);
        if (!array && ![Object.prototype, null].includes(Object.getPrototypeOf(item))) fail('INVALID_REQUEST');
        seen.add(item);
        const result = array ? [] : Object.create(null);
        const keys = Reflect.ownKeys(item);
        if (array && (item.length > 10000 || keys.length !== item.length + 1)) fail('INVALID_REQUEST');
        for (const key of keys) {
            if (array && key === 'length') continue;
            if (typeof key !== 'string' || (array && !/^(0|[1-9]\d*)$/.test(key))) fail('INVALID_REQUEST');
            bytes += Buffer.byteLength(key);
            const descriptor = Object.getOwnPropertyDescriptor(item, key);
            if (!Object.hasOwn(descriptor, 'value')) fail('INVALID_REQUEST');
            result[key] = copy(descriptor.value, depth + 1);
        }
        seen.delete(item);
        return result;
    }
    return copy(value, 0);
}
export function validateEnvelope(data) {
    if (!data || Array.isArray(data) || typeof data !== 'object'
        || Object.keys(data).length !== 3 || !['businessId', 'invoiceId', 'draft'].every(key => Object.hasOwn(data, key))
        || !businessIdValid(data.businessId) || !identity(data.invoiceId)
        || !/^[A-Za-z0-9_-]{1,128}$/.test(data.invoiceId) || /^__.*__$/.test(data.invoiceId)) fail('INVALID_REQUEST');
    return data;
}

// Domain codes are generated by the imported domain error types, not input.
// Only known field names survive; unknown-key paths can contain customer data.
const safePath = /^(customerId|customerName|customerEmail|customerAddress|currency|issueDate|dueDate|lineItems(?:\[\d{1,3}\](?:\.(?:id|description|quantity|unitPriceMinor|discountMinor|taxRateBps|taxCode|catalogItemId))?)?)$/;
export function safeError(error) {
    if (error instanceof SaveInvoiceDraftError) return error;
    if (error instanceof InvoiceDraftValidationError) {
        const result = new SaveInvoiceDraftError('INVALID_INVOICE_DRAFT');
        if (/^[A-Z_]{1,64}$/.test(error.code)) result.domainCode = error.code;
        if (typeof error.path === 'string' && error.path.trim() === error.path && safePath.test(error.path)) result.path = error.path;
        return result;
    }
    if (error instanceof InvoiceDraftCommandError) {
        return new SaveInvoiceDraftError(['BUSINESS_ACCESS_DENIED', 'INVALID_BUSINESS_ROLE', 'UNAUTHENTICATED'].includes(error.code)
            ? error.code : 'INTERNAL');
    }
    if ([6, 'already-exists'].includes(error?.code)) return new SaveInvoiceDraftError('INVOICE_ALREADY_EXISTS');
    if ([4, 8, 10, 14, 'ECONNREFUSED', 'ETIMEDOUT', 'app/network-error', 'auth/internal-error',
        'unavailable', 'deadline-exceeded'].includes(error?.code)) return new SaveInvoiceDraftError('UNAVAILABLE');
    return new SaveInvoiceDraftError('INTERNAL');
}
